# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _BASE_NS_/blockchain-baseimage:_BASE_TAG_ as builder
WORKDIR /opt/gopath
RUN mkdir src && mkdir pkg && mkdir bin
ADD . src/github.com/mcc-github/blockchain
WORKDIR /opt/gopath/src/github.com/mcc-github/blockchain
ENV EXECUTABLES go git curl
RUN make configtxgen configtxlator cryptogen peer

FROM _BASE_NS_/blockchain-baseimage:_BASE_TAG_
ENV FABRIC_CFG_PATH /etc/mcc-github/blockchain
RUN apt-get update && apt-get install -y jq
VOLUME /etc/mcc-github/blockchain
COPY --from=builder /opt/gopath/src/github.com/mcc-github/blockchain/.build/bin /usr/local/bin
COPY --from=builder /opt/gopath/src/github.com/mcc-github/blockchain/sampleconfig $FABRIC_CFG_PATH
